wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.16.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709106884.490514
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.9.13
      5: 0.16.3
      8:
      - 3
      - 5
      13: windows-amd64
alpha:
  desc: null
  value: 1.042614015071219
kernel_close:
  desc: null
  value: 3
kernel_open:
  desc: null
  value: 5
rho:
  desc: null
  value: 0.07833577410684461
