wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.16.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709082599.876813
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.9.13
      5: 0.16.3
      8:
      - 3
      - 5
      13: windows-amd64
alpha:
  desc: null
  value: 3.44797964200046
kernel_close:
  desc: null
  value: 11
kernel_open:
  desc: null
  value: 11
rho:
  desc: null
  value: 0.13789013088373406
