wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.16.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709123573.81143
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.9.13
      5: 0.16.3
      8:
      - 3
      - 5
      13: windows-amd64
alpha:
  desc: null
  value: 6.6648839220642975
colorSpace:
  desc: null
  value: hsv
kernel_close:
  desc: null
  value: 25
kernel_open:
  desc: null
  value: 5
rho:
  desc: null
  value: 0.017887581794677466
