wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.16.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709125638.950177
    t:
      1:
      - 55
      3:
      - 23
      4: 3.9.13
      5: 0.16.3
      8:
      - 3
      - 5
      13: windows-amd64
alpha:
  desc: null
  value: 12.03346874712452
colorSpace:
  desc: null
  value: hsv
kernel_close:
  desc: null
  value: 35
kernel_open:
  desc: null
  value: 11
rho:
  desc: null
  value: 0.10694693613767256
