wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.16.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709111135.232067
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      - 37
      4: 3.9.13
      5: 0.16.3
      8:
      - 3
      - 5
      13: windows-amd64
alpha:
  desc: null
  value: 11.684117697645634
kernel_close:
  desc: null
  value: 9
kernel_open:
  desc: null
  value: 7
rho:
  desc: null
  value: 0.18618972730549707
